
#---Q1. What is the total revenue generated by male vs. female customers ?
SELECT gender, SUM(purchase_amount) as Total_Revenue
FROM customer_behaviour.customer
GROUP BY gender;

#---Q2. Which customer used a discount but still spent more than the Average purchase amount ?
SELECT customer_id, purchase_amount
FROM customer_behaviour.customer
WHERE discount_applied ='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) 
													 FROM customer_behaviour.customer);
                                                     
#---Q3. Which are the top 5 products with the highest average review rating ?

SELECT item_purchased,
	ROUND(AVG(review_rating),2) AS Average_Product_Rating
FROM customer_behaviour.customer
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;

#---Q4. Compare the average purchase Amount between standard and Express Shipping.?

SELECT shipping_type,
		ROUND(AVG(purchase_amount),2) AS Average_Purchase_Amount
FROM customer_behaviour.customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#---Q5. Do subscribed customers spend more? Compare Average spend and total revenue between subscribers and non-subscribers.?

SELECT subscription_status,
	COUNT(customer_id) AS Total_Customers,
    ROUND(AVG(purchase_amount),2) AS Average_Spend_Revenue,
    ROUND(SUM(purchase_amount),2) AS Total_Revenue
FROM customer_behaviour.customer
GROUP BY subscription_status
ORDER BY Total_Revenue, Average_Spend_Revenue DESC;
	
#Q6. Which 5 products have the highest percentage of purchases with discounts applied ?

SELECT item_purchased,
	ROUND(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100,2) AS Discount_Rate
FROM customer_behaviour.customer
GROUP BY item_purchased
ORDER BY Discount_Rate DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the cost of each segment?
WITH customer_type as (
SELECT customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
FROM customer_behaviour.customer
)

SELECT customer_segment, 
		COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

#Q8. What are the top 3 most purchased products within each category ?

WITH item_counts AS (
SELECT category, item_purchased,
	COUNT(customer_id) AS Total_Orders,
    ROW_NUMBER()OVER(partition by category ORDER BY COUNT(customer_id)DESC) AS item_rank
FROM customer_behaviour.customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, Total_Orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are report buyers (More than 5 previous purchases) also likely to subscribe ?

SELECT subscription_status,
	COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour.customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each group ?

SELECT age_group,
	SUM(purchase_amount) AS Total_Revenue
FROM customer_behaviour.customer
GROUP BY age_group
ORDER BY Total_Revenue DESC;